import type { IconType } from 'react-icons'
import {
  SiAngular,
  SiCss,
  SiDocker,
  SiDotnet,
  SiEslint,
  SiGit,
  SiGithub,
  SiGooglefit,
  SiHtml5,
  SiJavascript,
  SiLaravel,
  SiLighthouse,
  SiMysql,
  SiNodedotjs,
  SiOllama,
  SiPython,
  SiReact,
  SiRender,
  SiSqlite,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWordpress,
} from 'react-icons/si'

export type SkillIcon = IconType

const skillIconMap: Record<string, SkillIcon> = {
  React: SiReact,
  'React Native': SiReact,
  'React & TypeScript': SiReact,
  'Next.js': SiNodedotjs,
  Angular: SiAngular,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  CSS3: SiCss,
  'Tailwind CSS': SiTailwindcss,
  'C# / .NET': SiDotnet,
  '.NET / C#': SiDotnet,
  'PHP / Laravel': SiLaravel,
  Docker: SiDocker,
  Ollama: SiOllama,
  'Ollama & Python': SiOllama,
  Render: SiRender,
  Vercel: SiVercel,
  Git: SiGit,
  GitHub: SiGithub,
  'Git & GitHub': SiGithub,
  WordPress: SiWordpress,
  Python: SiPython,
  Vite: SiVite,
  Supabase: SiSupabase,
  MySQL: SiMysql,
  SQLite: SiSqlite,
  'MySQL & SQLite': SiMysql,
  'Health Tech': SiGooglefit,
  'UI responsive': SiCss,
  'Performance & UX': SiLighthouse,
  'Clean code': SiEslint,
}

const skillKeywordRules: [RegExp, SkillIcon][] = [
  [/supabase/i, SiSupabase],
  [/vite/i, SiVite],
  [/sqlite/i, SiSqlite],
  [/mysql/i, SiMysql],
  [/vercel/i, SiVercel],
  [/render/i, SiRender],
  [/docker/i, SiDocker],
  [/ollama/i, SiOllama],
  [/laravel|php/i, SiLaravel],
  [/ocr|health/i, SiGooglefit],
  [/responsive/i, SiCss],
  [/performance|ux/i, SiLighthouse],
  [/clean\s*code/i, SiEslint],
  [/github/i, SiGithub],
  [/git/i, SiGit],
  [/typescript/i, SiTypescript],
  [/react/i, SiReact],
  [/next\.?js/i, SiNodedotjs],
  [/angular/i, SiAngular],
  [/javascript/i, SiJavascript],
  [/tailwind/i, SiTailwindcss],
  [/html\s*5?/i, SiHtml5],
  [/css\s*3?/i, SiCss],
  [/python/i, SiPython],
  [/wordpress/i, SiWordpress],
  [/(\.net|c#)/i, SiDotnet],
  [/node\.?js/i, SiNodedotjs],
]

export function getSkillIcon(skill: string): SkillIcon | undefined {
  const exact = skillIconMap[skill]
  if (exact) return exact

  return skillKeywordRules.find(([pattern]) => pattern.test(skill))?.[1]
}
